/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, Item, Category } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    email: '6531501001@lamduan.mfu.ac.th',
    name: 'Somchai Rakdee',
    studentId: '6531501001',
    faculty: 'Information Technology',
    role: 'student',
    isBanned: false,
    wishlist: [],
    cart: [],
    orderHistory: [],
    phoneNumber: '081-234-5678',
  },
  {
    id: 'u2',
    email: '6531501002@lamduan.mfu.ac.th',
    name: 'Jane Doe',
    studentId: '6531501002',
    faculty: 'Management',
    role: 'student',
    isBanned: false,
    wishlist: [],
    cart: [],
    orderHistory: [],
    phoneNumber: '082-345-6789',
  },
  {
    id: 'admin1',
    email: 'admin@mfu.ac.th',
    name: 'Admin User',
    studentId: '0000000000',
    faculty: 'Office of IT',
    role: 'admin',
    isBanned: false,
    wishlist: [],
    cart: [],
    orderHistory: [],
    phoneNumber: '080-000-0000',
  },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'i1',
    sellerId: 'u1',
    sellerName: 'Somchai Rakdee',
    title: 'Calculus Textbook',
    description: 'Used for 1 semester, good condition. No highlights.',
    price: 250,
    category: 'Books',
    images: ['https://picsum.photos/seed/calculus/400/300'],
    status: 'available',
    stock: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'i2',
    sellerId: 'u2',
    sellerName: 'Jane Doe',
    title: 'Desk Lamp',
    description: 'Bright LED lamp, adjustable neck. Perfect for late night study.',
    price: 150,
    category: 'Electronics',
    images: ['https://picsum.photos/seed/desklamp/400/300'],
    status: 'available',
    stock: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'i3',
    sellerId: 'u1',
    sellerName: 'Somchai Rakdee',
    title: 'MFU Hoodie',
    description: 'Size L, worn twice. Very warm.',
    price: 400,
    category: 'Clothing',
    images: ['https://picsum.photos/seed/hoodie/400/300'],
    status: 'available',
    stock: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'i4',
    sellerId: 'u2',
    sellerName: 'Jane Doe',
    title: 'Wooden Study Desk',
    description: 'Compact wooden desk, minor scratches but very sturdy.',
    price: 800,
    category: 'Furniture',
    images: ['https://picsum.photos/seed/studydesk/400/300'],
    status: 'available',
    stock: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'i5',
    sellerId: 'u1',
    sellerName: 'Somchai Rakdee',
    title: 'Scientific Calculator',
    description: 'Casio FX-991ES Plus. Works perfectly.',
    price: 350,
    category: 'Stationery',
    images: ['https://picsum.photos/seed/calculator/400/300'],
    status: 'available',
    stock: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'i6',
    sellerId: 'u2',
    sellerName: 'Jane Doe',
    title: 'Drawing Pens Set',
    description: 'Set of 12 professional drawing pens. Unused.',
    price: 120,
    category: 'Stationery',
    images: ['https://picsum.photos/seed/pens/400/300'],
    status: 'available',
    stock: 5,
    createdAt: new Date().toISOString(),
  },
];

export const CATEGORIES: Category[] = [
  'Electronics',
  'Books',
  'Clothing',
  'Furniture',
  'Stationery',
  'Other',
];
